### ISSUE TITLE
how can i use it

### ISSUE THREAD

**Issue by SimplyY** [mark-hahn/html-tab#2]
only it i can see .T_T

![image](https://cloud.githubusercontent.com/assets/8455579/9079132/694bf65e-3b79-11e5-8bd5-72ce443904bc.png)

**Comment by mark-hahn** [comment]
That is all it does.  It is a sample package.  It is there for you to read
the source code and learn how to put your own HTML in editor tabs.  The
README explains this.

**Comment by SimplyY** [comment]
thanks ,i get it

**Comment by sandcobainer** [comment]
@mark-hahn This is an amazing resource to get started for beginners. Thank you. I was looking for some documentation to write detailed HTML views in the CoffeeScript classes. Mostly stuff like including external Javascript files, CSS styling in the view. IS this possible? 

I couldn't find any documentation or examples on this maybe because atom space pen views are deprecated from the Atom Core? Do you know any other resources lying on the internet somewhere?

**Comment by mark-hahn** [comment]
I'm sorry.  I haven't used atom in several years.
